steps:
  - name: "alexz-demo-pipeline"
    agents:
      queue: elastic
    commands:
      - "echo 'Hello this world' "
    timeout_in_minutes: 15
    
  - command:
    - "ls"
    - "scripts/trigger-github-deploy"
    key: trigger-github-deploy
    agents:
      queue: elastic


  - input: "what is the name of your repo?"
    fields:
      - text: "Your name"
        key: "name"
  - label: "Run script"
    command: "scripts/auto-create-repo"

  - command:
    - "scripts/auto-create-repo"
    key: auto-create-repo
    agents:
      queue: elastic
  
  



