steps:
  - name: "alexz-demo-pipeline"
    agents:
      queue: elastic
    commands:
      - "echo 'Hello this world' "
    timeout_in_minutes: 15
    
  - command:
    - "cat README.md"
    #- "ls"
    #- "pwd"
    #- "cat scripts/trigger-github-deploy"
    key: trigger-github-deploy
    agents:
      queue: elastic


