steps:
  - name: "alexz-demo-pipeline"
    agents:
      queue: elastic
    commands:
      - "echo 'Hello this world' "
    timeout_in_minutes: 15
    
  - command:
    - "ls"
    - "scripts/trigger-github-deploy"
    key: trigger-github-deploy
    agents:
      queue: elastic


  - input: "Name your repo"
    fields:
      - text: "Your name"
        key: "name"
  - label: "Run script"
    command: scripts/auto-create-repo
    agents: 
      queue: elastic
  #- notify:
  #  command: echo "HELLO"
  #    if: "name" == "alexneedfood"


#  - command:
#    - "scripts/auto-create-repo"
#    key: auto-create-repo
#    agents:
#      queue: elastic
  
  



