steps:
  - name: "alexz-demo-pipeline"
    agents:
      queue: elastic
    commands:
      - "echo 'Hello this world' "
    timeout_in_minutes: 15
    
  - command:
    - "ls"
    - "scripts/trigger-github-deploy"
    key: trigger-github-deploy
    agents:
      queue: elastic


  - input: "Name your repo"
    fields:
      - text: "Your name"
        key: "name"
  - label: "Run script"
    command: scripts/auto-create-repo
    agents: 
      queue: elastic

actions:
- action: "EMAIL Action"
  type: "EMAIL"
  title: "test"
  from_name: "Alex"
  content: "<b>${BUDDY_PIPELINE_NAME}</b> execution #${BUDDY_EXECUTION_ID}"
  recipients: "alexneedfood@gmail.com"
  send_as_html: true
  variables:
  - key: "title"
    value: "Pipeline executed successfully!"
  
#notify:
#  - email: "alexneedfood@gmail.com"
#    content: "yes"
    #if: build.state == "passed"
  #  command: echo "HELLO"
  #    if: "name" == "alexneedfood"


#  - command:
#    - "scripts/auto-create-repo"
#    key: auto-create-repo
#    agents:
#      queue: elastic
  
  



