#!/bin/bash
set -euo pipefail

if [[ "$BUILDKITE_PIPELINE_SLUG" == "my-app" ]]; then
  if [[ "$BUILDKITE_STEP_KEY" == "trigger-github-deploy" ]]; then
    export GITHUB_MY_APP_DEPLOYMENT_ACCESS_TOKEN="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"
  fi
fi