#!/bin/bash
NAME=""

until [ ${#NAME} -gt 0 ]
do
  echo "Script is checking for name"
  NAME=$(buildkite-agent meta-data get name)
  echo "Script run by $NAME"
  sleep 5
done


curl -H "Authorization: token $GITHUB_MY_APP_DEPLOYMENT_ACCESS_TOKEN" \
    --data '{"name":"'$NAME'"}'\
    https://api.github.com/user/repos


#if curl -fsS "https://api.github.com/repos/$MY_REPO" >/dev/null; then
#    echo '%s\n' "The GitHub repo $MY_REPO exists this is me." >&2
#    return 0
#else
#    printf '%s\n' "Error: no GitHub repo $MY_REPO found." >&2
#    return 1
#fi

if [ "$MY_REPO" = "$NAME" ]; then
    echo "Strings are equal."
else
    echo "Strings are not equal."
fi


