#!/bin/bash
NAME=""

until [ ${#NAME} -gt 0 ]
do
  echo "Script is checking for name"
  NAME=$(buildkite-agent meta-data get name)
  echo "Script run by $NAME"
  sleep 5
done

if curl -fsS "https://api.github.com/repos/Alexandrazhao/$NAME" >/dev/null; then
    printf '%s\n' "The GitHub repo $NAME exists." >&2
    -o "file_#1.txt"
else
    printf '%s\n' "Error: no GitHub repo $NAME found. Creating a new one now..." >&2
    curl -H "Authorization: token $GITHUB_MY_APP_DEPLOYMENT_ACCESS_TOKEN" \
    --data '{"name":"'$NAME'"}'\
    https://api.github.com/user/repos -o "file_#1.txt"
    curl -X PUT \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token $GITHUB_MY_APP_DEPLOYMENT_ACCESS_TOKEN" \
        https://api.github.com/repos/Alexandrazhao/$NAME/contents/readme -o "file_#3.txt"  \
        https://api.github.com/repos/Alexandrazhao/$NAME/contents/test.txt -o "file_#2.txt"  \
        -d '{"message":"my commit message","committer":{"name":"Alex","email":"alexneedfood@gmail.com"},"content":"VGhpcyBpcyBhIGF1dG9tYWljYWxseSBnZW5lcmF0ZWQgZG9jdW1lbnQuIA=="}'
    curl -X PUT \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token $GITHUB_MY_APP_DEPLOYMENT_ACCESS_TOKEN" \
        https://api.github.com/repos/Alexandrazhao/$NAME/contents/readme1 -o "file_#5.txt"  \
        https://api.github.com/repos/Alexandrazhao/$NAME/contents/manage.py -o "file_#6.txt"  \
        -d '{"message":"my commit message","committer":{"name":"Alex","email":"alexneedfood@gmail.com"},"content":"IyEvdXNyL2Jpbi9lbnYgcHl0aG9uCiIiIkRqYW5nbydzIGNvbW1hbmQtbGluZSB1dGlsaXR5IGZvciBhZG1pbmlzdHJhdGl2ZSB0YXNrcy4iIiIKaW1wb3J0IG9zCmltcG9ydCBzeXMKCgpkZWYgbWFpbigpOgogICAgb3MuZW52aXJvbi5zZXRkZWZhdWx0KCdESkFOR09fU0VUVElOR1NfTU9EVUxFJywgJ0xpYnJhcnkuc2V0dGluZ3MnKQogICAgdHJ5OgogICAgICAgIGZyb20gZGphbmdvLmNvcmUubWFuYWdlbWVudCBpbXBvcnQgZXhlY3V0ZV9mcm9tX2NvbW1hbmRfbGluZQogICAgZXhjZXB0IEltcG9ydEVycm9yIGFzIGV4YzoKICAgICAgICByYWlzZSBJbXBvcnRFcnJvcigKICAgICAgICAgICAgIkNvdWxkbid0IGltcG9ydCBEamFuZ28uIEFyZSB5b3Ugc3VyZSBpdCdzIGluc3RhbGxlZCBhbmQgIgogICAgICAgICAgICAiYXZhaWxhYmxlIG9uIHlvdXIgUFlUSE9OUEFUSCBlbnZpcm9ubWVudCB2YXJpYWJsZT8gRGlkIHlvdSAiCiAgICAgICAgICAgICJmb3JnZXQgdG8gYWN0aXZhdGUgYSB2aXJ0dWFsIGVudmlyb25tZW50PyIKICAgICAgICApIGZyb20gZXhjCiAgICBleGVjdXRlX2Zyb21fY29tbWFuZF9saW5lKHN5cy5hcmd2KQoKCmlmIF9fbmFtZV9fID09ICdfX21haW5fXyc6CiAgICBtYWluKCk="}'
        #-d '{"message":"my commit message","committer":{"name":"Alex","email":"alexneedfood@gmail.com"},"content":"YW5vdGhlciBmaWxl"}'
fi
#sleep 20

#curl -H "Authorization: token $GITHUB_MY_APP_DEPLOYMENT_ACCESS_TOKEN" \
#    --data '{"name":"'$NAME'"}'\
#    https://api.github.com/user/repos

#curl -X PUT \
#  -H "Accept: application/vnd.github.v3+json" \
#  -H "Authorization: token $GITHUB_MY_APP_DEPLOYMENT_ACCESS_TOKEN" \
#  https://api.github.com/repos/Alexandrazhao/$NAME/contents/readme \
#  https://api.github.com/repos/Alexandrazhao/$NAME/contents/test.txt \
#  -d '{"message":"my commit message","committer":{"name":"Alex","email":"alexneedfood@gmail.com"},"content":"VGhpcyBpcyBhIGF1dG9tYWljYWxseSBnZW5lcmF0ZWQgZG9jdW1lbnQuIA=="}'




#if [ "$MY_REPO" = "$NAME" ]; then
#    echo "Strings are equal."
#else
#    echo "Strings are not equal. my-repo is $MY_REPO, my name is $NAME"
#fi


