#!/bin/bash
NAME=""

until [ ${#NAME} -gt 0 ]
do
  echo "Script is checking for name"
  NAME=$(buildkite-agent meta-data get name)
  echo "Script run by $NAME"
  sleep 5
done

if curl https://api.github.com/repos/Alexandrazhao/$NAME; then
    echo '%s\n' "The GitHub repo $NAME exists this is me." >&2
else
    printf '%s\n' "Error: no GitHub repo $NAME found." >&2
fi
sleep 20

curl -H "Authorization: token $GITHUB_MY_APP_DEPLOYMENT_ACCESS_TOKEN" \
    --data '{"name":"'$NAME'"}'\
    https://api.github.com/user/repos




#if [ "$MY_REPO" = "$NAME" ]; then
#    echo "Strings are equal."
#else
#    echo "Strings are not equal. my-repo is $MY_REPO, my name is $NAME"
#fi


