#!/bin/bash
set -euo pipefail

curl \
  --header "Authorization: token $GITHUB_MY_APP_DEPLOYMENT_ACCESS_TOKEN" \
  --request POST \
  --data "{\"ref\": \"$BUILDKITE_COMMIT\"}" \
  https://api.github.com/repos/Alexandrazhao/auto-github-repo/